In [1]:
import numpy as np

Recursive function for determinant

In [2]:
def determ(A):
    
    A = np.array(A)
    
    assert (len(A.shape) == 2), "Input matrix must be a 2D matrix: is {}D".format(len(A.shape))
    assert (A.shape[0] == A.shape[1]), "Input matrix must be a square matrix: has {} rows and {} columns".format(A.shape[0],A.shape[1])
    
    if A.shape == (1,1):
        return A[0,0]
    
    else: 
        result = 0
        for i in np.arange(A.shape[0]):
            result += ((-1) ** i)*A[i, 0]*determ(np.delete(np.delete(A, i, 0), 0, 1))
        return result

Examples

In [3]:
a=np.array([[1,3],[3,2]])
print(determ(a))

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(determ(a))

a = np.array([[1,2,3,4,5],[4,7,3,2,1],[5,7,0,1,3],[3,4,6,1,3],[0,4,7,1,2]])
print(determ(a))

-7
0
1368


Random Stuff because I am an e

In [36]:
print(1/(1+np.exp(-np.array([1,2,3]))))

import math
[1/(1+math.exp(-y)) for y in np.array([1,2,3])]

[0.73105858 0.88079708 0.95257413]


[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]

In [88]:
# 5 words, 3 embeddings
U = np.array([[1,2,3,4,5],[5,4,2,6,7],[10,9,5,91,10]])
v_c = np.array([1,2,3])
outsideWordIdx = 1

y = np.zeros(U.shape[1])
y[outsideWordIdx] = 1
print(y)

# Compute 'y hat'
u_o = U[:, outsideWordIdx]
denominator = np.sum((U.T * v_c), axis=1)
print(denominator)
numerator = denominator[outsideWordIdx]
print(numerator)
y_hat = softmax(denominator)

#print(denominator)
print(y_hat)

y_hat.shape = (5, 1)
v_c.shape = (3, 1)
print(v_c)

print(v_c * y_hat.T)
print('abc')

print(y_hat[outsideWordIdx])
print(y_hat[outsideWordIdx] * v_c - v_c)

[0. 1. 0. 0. 0.]
[ 41  37  22 289  49]
37
[1.97227962e-108 3.61235614e-110 1.10502813e-116 1.00000000e+000
 5.87928270e-105]
[[1]
 [2]
 [3]]
[[1.97227962e-108 3.61235614e-110 1.10502813e-116 1.00000000e+000
  5.87928270e-105]
 [3.94455925e-108 7.22471228e-110 2.21005625e-116 2.00000000e+000
  1.17585654e-104]
 [5.91683887e-108 1.08370684e-109 3.31508438e-116 3.00000000e+000
  1.76378481e-104]]
abc
[3.61235614e-110]
[[-1.]
 [-2.]
 [-3.]]


In [70]:
print(np.exp(41)/(np.exp(41)+np.exp(37)+np.exp(22)+np.exp(289)+np.exp(49)))
print(np.exp(37)/(np.exp(41)+np.exp(37)+np.exp(22)+np.exp(289)+np.exp(49)))
print(np.exp(22)/(np.exp(41)+np.exp(37)+np.exp(22)+np.exp(289)+np.exp(49)))
print(np.exp(289)/(np.exp(41)+np.exp(37)+np.exp(22)+np.exp(289)+np.exp(49)))
print(np.exp(49)/(np.exp(41)+np.exp(37)+np.exp(22)+np.exp(289)+np.exp(49)))

1.9722796241351285e-108
3.6123561383267394e-110
1.105028125193164e-116
1.0
5.8792826982452694e-105


In [68]:
print((U.T * v_c).T)
print(np.sum((U.T * v_c).T, axis=0))
print(np.sum((U.T * v_c).T, axis=1))

[[  1   2   3   4   5]
 [ 10   8   4  12  14]
 [ 30  27  15 273  30]]
[ 41  37  22 289  49]
[ 15  48 375]


In [52]:
outsideWordIdx = 1

y = np.zeros(U.shape[1])
y[outsideWordIdx] = 1

y

array([0., 1., 0., 0., 0.])

In [25]:
-np.log((U.T * v_c).T)

array([[-0.        , -0.69314718, -1.09861229, -1.38629436, -1.60943791],
       [-2.30258509, -2.07944154, -1.38629436, -2.48490665, -2.63905733],
       [-3.40119738, -3.29583687, -2.7080502 , -5.6094718 , -3.40119738]])

In [27]:
y=np.zeros(U.shape[1])
y[1] = 1
y

array([0., 1., 0., 0., 0.])

array([[0., 2., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 9., 0., 0., 0.]])

In [29]:
def softmax(x):
    """Compute the softmax function for each row of the input x.
    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. 

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.
    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape

    if len(x.shape) > 1:
        # Matrix
        tmp = np.max(x, axis=1)
        x -= tmp.reshape((x.shape[0], 1))
        x = np.exp(x)
        tmp = np.sum(x, axis=1)
        x /= tmp.reshape((x.shape[0], 1))
    else:
        # Vector
        tmp = np.max(x)
        x -= tmp
        x = np.exp(x)
        tmp = np.sum(x)
        x /= tmp

    assert x.shape == orig_shape
    return x

softmax(np.array([1,4,2]))

array([0.04201007, 0.84379473, 0.1141952 ])

1.1535649948951077